### ISSUE TITLE
HTML parser implementation

### ISSUE THREAD

**Issue by kewynakshlley** [zachzurn/thermal#3]
I would like to help/contribute to the repository with the HTML Parser, do you have already some draft about it? If you have any suggestion on how to approach this problem, it would be helpful. After creating this feature, I could try to extend it to markdown and so on. Also, would be great to have this library published, it's really powerful and deserves to be published.

**Comment by zachzurn** [comment]
I have the html renderer in progress. The html renderer will output a single html file with embedded style and images. There are some challenges with font scaling that I'm running into.

If you want to work on a markdown renderer, you can have a look at the image renderer for how to implement it. You will most likely need to export images separately, since I'm not aware of image embedding.

**Comment by kewynakshlley** [comment]
That's good news. It will be really useful as it would remove the overhead of converting it in client applications. Don't hesitate in committing this feature with minor issues. Thanks a lot.

**Comment by zachzurn** [comment]
I pushed the initial html renderer. Give it a go.

**Comment by kewynakshlley** [comment]
I worked as a charm, thanks a lot.
