### ISSUE TITLE
Scaling depending on the printer model

### ISSUE THREAD

**Issue by kewynakshlley** [zachzurn/thermal#6]
Some printers generate really thick bars in the barcode, ex:

```
 let point_width = context.barcode.width = 10;
 let point_height = context.barcode.height = 64;
```

In that case, the barcodes become unreadable because of the thickness of the bars. I tried changing the scale, but it didn't work. Do you have any clue about the solution for this?

OBS:  it happens for all barcodes generated for this specific printer. In order to reproduce it, you can just set the width to 10 and heigth to 64 harcoded.

**Comment by zachzurn** [comment]
Can you send me the binary for that barcode command? I assumed the width is the pixel width of each bar but maybe I'm wrong on the implementation.

**Comment by kewynakshlley** [comment]
Here is the link with the file: https://drive.google.com/file/d/1tT80VIXjlsVaXCeFIkBwkUv7kimcgXZJ/view?usp=sharing, cant send files here.

**Comment by kewynakshlley** [comment]
Also, just noticed it, it's cutting part of the barcode.

**Comment by zachzurn** [comment]
Looking through the spec, it seems like GS w is in fact the width of each bar, so a 10 would be really thick.

https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=129

I could add some kind of override option into the context like force_single_barcode_width which would force all barcode width settings to use `1` instead of the context width.

There is this other line in the spec which I don't quite understand that may be related:

When the barcode height set with [GS h](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=127#gs_lh) is smaller than [33 times the module width], a barcode with a height (excluding the HRI characters) of [module width × 33] is printed, without reference to the [GS h](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=127#gs_lh) setting.

**Comment by zachzurn** [comment]
I think we can limit the min to 2 and the max to 6, and divide the number in half for the pixel width. 

```
w   value     px
1       2          1
10     6         3 
```

**Comment by kewynakshlley** [comment]
What do you mean by “The width value that gets set on the context is divided by 2”? I didn't get the point.

**Comment by zachzurn** [comment]
I'll see if I can implement and test to see if my idea works. It's a but hard to explain until I can get back into the code.

The 2 and 6 limits come from this: https://python-escpos.readthedocs.io/en/latest/user/barcode.html
